// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::liftMechanismLiftMotor = NULL;
SpeedController* RobotMap::driveMechanismLeftMotor = NULL;
SpeedController* RobotMap::driveMechanismRightMotor = NULL;
RobotDrive* RobotMap::driveMechanismRobotDrive = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	liftMechanismLiftMotor = new Talon(4);
	lw->AddActuator("LiftMechanism", "LiftMotor", (Talon*) liftMechanismLiftMotor);
	
	driveMechanismLeftMotor = new Talon(0);
	lw->AddActuator("DriveMechanism", "LeftMotor", (Talon*) driveMechanismLeftMotor);
	
	driveMechanismRightMotor = new Talon(1);
	lw->AddActuator("DriveMechanism", "RightMotor", (Talon*) driveMechanismRightMotor);
	
	driveMechanismRobotDrive = new RobotDrive(driveMechanismLeftMotor, driveMechanismRightMotor);
	
	driveMechanismRobotDrive->SetSafetyEnabled(true);
        driveMechanismRobotDrive->SetExpiration(0.1);
        driveMechanismRobotDrive->SetSensitivity(0.5);
        driveMechanismRobotDrive->SetMaxOutput(1.0);
        



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
